version: '3'


services:

  app:
    build:
      context: ./
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - "postgres"

  postgres:
    image: postgres
    volumes:
      - ./migration/01-db.sql:/docker-entrypoint-initdb.d/01-db.sql
    environment:
      POSTGRES_USER: "uDB"
      POSTGRES_PASSWORD: "pDB!"
    ports:
      - "5432:5432"