version: '3'


services:

  app:
    build: 
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - "redis"

  redis:
    image: redis
    command: redis-server
    ports:
      - "127.0.0.1:6379:6379"
    