###
# token token_abcd on /
GET http://localhost:8080/
API_TOKEN: token_abcd
###
# token token_abcd on /page-1
GET http://localhost:8080/page-1
API_TOKEN: token_abcd
###
# token token_novo on /
GET http://localhost:8080/
API_TOKEN: token_novo
###
# token token_novo on /page-2
GET http://localhost:8080/page-2
API_TOKEN: token_novo
###
# ip 192.168.0.1 on /
GET http://localhost:8080/
X-Real-IP: 192.168.0.1
###
# ip 192.168.0.1 on /page-1
GET http://localhost:8080/page-1
X-Real-IP: 192.168.0.1
###
# ip 192.168.0.10 on /
GET http://localhost:8080/
X-Forwarded-For: 192.168.0.10
###
# ip 192.168.0.10 on /page-2
GET http://localhost:8080/page-2
X-Forwarded-For: 192.168.0.10
###
# ip default on /
GET http://localhost:8080/
###
# ip default on /page-1
GET http://localhost:8080/page-1