// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID          string  `json:"id"`
	Description string  `json:"description"`
	Qty         int     `json:"qty"`
	Value       float64 `json:"value"`
	Order       *Order  `json:"order"`
}

type Mutation struct {
}

type NewItem struct {
	Description string  `json:"description"`
	Qty         int     `json:"qty"`
	Value       float64 `json:"value"`
	OrderID     string  `json:"orderId"`
}

type NewOrder struct {
	Data string `json:"data"`
}

type Order struct {
	ID    string  `json:"id"`
	Data  string  `json:"data"`
	Items []*Item `json:"items"`
}

type Query struct {
}
