
query ListOrders {
  orders {
    id
    data
    items {
      id
      description
      qty
      value
    }
  }
}

mutation createOrder {
  createOrder(input: {data: "teste"}) {
    id
    data
  }
}

query queryOrder {
  orders {
    id
    data
  }
}

query queryOrderAndItem {
  orders {
    id
    data
    items {
      id
      description
      qty
      value
    }
  }
}

mutation createItem {
  createItem(
    input: {orderId: "96379b15-82ed-4516-b0eb-48b27b80eab2", description: "item 1", qty: 2, value: 9.99}
  ) {
    id
    description
    qty
    value
  }
}

query queryItem {
  items {
    id
    description
    qty
    value
  }
}

query queryItemAndOrder {
  items {
    id
    description
    qty
    value
    order {
      id
    }
  }
}