version: '3'

services:

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./telemetria/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin-slim:latest
    restart: always
    depends_on:
      - otel-collector
    ports:
      - "9411:9411"

#http://app-zipcode:8080
#http://app-weather:8090
  api-temperature:
    build:
      context: ./api-temperature
    environment:
      - HTTP_PORT=:8090
      - TOKEN=2d4fc12c862a4c3bbd5234402242607
      - WEATHER_ENDPOINT=http://api-temperature:8090/weather
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - REQUEST_NAME_OTEL=ms-temperature-request
      - SPAN_TRACE_NAME=service-b-temperature
    ports:
      - "8090:8090"
    depends_on:
      - zipkin
      - otel-collector


  api-zipcode:
    build:
      context: ./api-proxy
    environment:
      - HTTP_PORT=:8080
      - WEATHER_ENDPOINT=http://api-temperature:8090
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - REQUEST_NAME_OTEL=ms-zipcode-request
      - SPAN_TRACE_NAME=service-a-zipcode
    ports:
      - "8080:8080"
    depends_on:
      - api-temperature
      - zipkin
      - otel-collector
