###
###
###
### zipcode
GET http://localhost:8090/zipcode?zipcode=02765070
Content-Type: application/json
### weather
GET http://localhost:8090/weather?city=brasilia&uf=df
Content-Type: application/json
###
# weather ok
GET http://localhost:8090/weather?city=sp&uf=sp
Content-Type: application/json
###
# weather ok
GET http://localhost:8090/weather?city=nova+city&uf=
Content-Type: application/json
###
# weather ok
GET http://localhost:8090/weather?city=nova+olinda&uf=pi
Content-Type: application/json
###
# 200 ok
GET http://localhost:8090/weather?city=sao+paulo&uf=sp
Content-Type: application/json

###
# 400 ok ZIPCODE + WEATHER
POST http://localhost:8080
Content-Type: application/json

{
    "cep": "02765070"
}

###
# 422 Unprocessable Entity
POST http://localhost:8080
Content-Type: application/json

{
    "cep": "0276507"
}

###
# 404 not found
POST http://localhost:8080
Content-Type: application/json

{
    "cep": "12345678"
}

###
# 422 not found
POST http://localhost:8080
Content-Type: application/json

{
    "cep": ""
}
###
# 422 not found
POST http://localhost:8080
Content-Type: application/json
