GET http://localhost:8080/users

###

GET http://localhost:8080/users/1

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 2,
  "name": "xpto",
  "account": {
    "id": 2,
    "number": "1234",
    "agency": "123",
    "balance": 100,
    "limit": 1000
  },
  "card": {
    "id": 2,
    "number": "1234 1234 1234 1234",
    "limit": 500
  },
  "features": [
    {
      "id": 1,
      "icon": "no",
      "description": "gasto"
    }
  ],
  "news": [
    {
      "id": 1,
      "icon": "no",
      "description": "novi"
    }
  ]
}