apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    # kubernetes.io/ingress.class: nginx
    spec.ingressClassName: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: acme.com
    - http:
        paths:
          - path: /api/platform
            pathType: Prefix
            backend:
              service:
                name: platforms-clusterip-srv # same file "platform-depl.yaml" service name
                port:
                  number: 80
          - path: /api/c/platforms
            pathType: Prefix
            backend:
              service:
                name: commands-clusterip-srv # same file "commands-depl.yaml" service name
                port:
                  number: 80
