apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-standard
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv
  labels:
    name: local-pv
spec:
  capacity:
    storage: 5Gi
  storageClassName: local-standard #manual
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/c/dev/disk_mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
spec:
  storageClassName: local-standard #manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: local-pv
