apiVersion: v1
kind: Service
metadata:
  name: platformservice-srv
spec:
  type: NodePort
  selector:
    app: platformservice
  # equals name from depl file
  ports:
    - name: platformservice
      protocol: TCP
      port: 80
      targetPort: 80
#  externalIPs:
#  - "10.109.90.30"