// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewItem struct {
	Description string  `json:"description"`
	Qty         int     `json:"qty"`
	Value       float64 `json:"value"`
	OrderID     string  `json:"orderId"`
}

type NewOrder struct {
	Data string `json:"data"`
}

type Query struct {
}
