version: '3.8'

services:
  db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: java-board
      MYSQL_PASSWORD: java-board
      MYSQL_DATABASE: java-board
    ports:
      - "3306:3306"
