# podman / docker
@URL_LOCAL_8080 = http://localhost:6000
@URL_ACME = http://acme.com
@URL_DOCKER = http://localhost:8080

@URL_LOCAL = http://localhost

@URL_KIND = https://127.0.0.1:62349
@URL_KIND = https://127.0.0.1:30407

@URL = {{URL_LOCAL}}

###
GET {{URL}}/api/c/platforms
Accept: application/json
