# podman / docker
@URL_LOCAL_8080 = http://localhost:6000
@URL_ACME = http://acme.com
@URL_DOCKER = http://localhost:8080

@URL_LOCAL = http://localhost

@URL_MINIKUBE = http://10.105.167.179
@URL_KIND = http://127.0.0.1:30407

@URL = {{URL_ACME}}
@URL = {{URL_MINIKUBE}}

#@URL = http://10.105.167.179

###
GET http://127.0.0.1:8080


###
GET {{URL}}/api/platforms
Accept: application/json

###

GET {{URL}}/api/platforms/1
Accept: application/json

###

POST {{URL}}/api/platforms
Content-Type: application/json

{
    "name": "teste",
    "publisher": "teste",
    "cost": "teste"
}

###
GET  {{URL}}/api/Platform/4
Accept: application/json